### ISSUE TITLE
Passwords

### ISSUE THREAD

**Issue by Million900o** [Million900o/ShareX-Server#9]
Use bcrypt or smth to make better passwords security pls, I don't want u to leak my passwords!!!

**Comment by Million900o** [comment]
> Use bcrypt or smth to make better passwords security pls, I don't want u to leak my passwords!!!

Got it will do.

**Comment by flazepe** [comment]
yes

**Comment by Million900o** [comment]
> yes

I agree

**Comment by Million900o** [comment]
Fixed!
